server:
  port: 8080
spring:
    application:
      name: securityDemo3
    datasource:
      url: jdbc:mysql://localhost:3306/sys_user?characterEncoding=UTF-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    redis:
        host: localhost
        port: 6379
        database: 1
mybatis:
  type-aliases-package: com.zhsw.sercuritydemo3.entity
  mapper-locations: classpath:mapper/*.xml
eureka:
 client:
    service-url:
      defaultZone: http://localhost:8030/eureka/
